version: '3'

dotenv: ['.env']

env:
  DOCKER_BUILDKIT: "1"

tasks:

  default:
    cmds:
      - go run .
  2:
    cmds:
      - DB_PATH="./dbs2" INSTANCE_ID=testinstance2 INTERNAL_PORT=8291 API_PORT=8290 GOSSIP_PORT=8292 BACKUP=1 KAFKA_SESSION_MS=7000 ADVERTISE_ADDR=localhost:8290 GOSSIP_PEERS=localhost:8192 go run .
  docker:
    cmds:
      - docker build . -t firescroll:latest --ssh default
  linux_amd:
    cmds:
      - GOOS=linux GOARCH=amd64 go build .
