### Put records
POST http://localhost:8190/records/put
Content-Type: application/json

{
  "Records": [
    {
      "pk": "pk1",
      "sk": "sk1",
      "data": {
        "hey": "ho"
      }
    },
    {
      "pk": "pk3",
      "sk": "sk3",
      "data": {
        "lets": "go"
      }
    }
  ]
}

### Get records
POST http://localhost:8190/records/get
Content-Type: application/json

{
  "Keys": [
    {
      "pk": "pk1",
      "sk": "sk1"
    },
    {
      "pk": "pk2",
      "sk": "sk2"
    },
    {
      "pk": "pk3",
      "sk": "sk3"
    }
  ]
}

### Delete records
POST http://localhost:8190/records/delete
Content-Type: application/json

{
  "Records": [
    {
      "pk": "pk1",
      "sk": "sk1"
    }
  ]
}